hostname: chianti
jobid: 123456
collectiondir: /home/mpotts/gfortran_9.3.0_openmpi_g_develop
scheduler: None
artifactsdir: /home/mpotts/esmf-test-artifacts
scriptdir: /home/mpotts/esmf-test-scripts/python_scripts
branch: develop
mpiversion: 3.1.3

