hostname: hera
scheduler: "slurm"
artifactsdir: /scratch1/NCEPDEV/stmp2/Mark.Potts/ufs-test-artifacts
scriptdir: /scratch1/NCEPDEV/stmp2/Mark.Potts/ufs-test-artifacts
ufsdir: /scratch1/NCEPDEV/da/Mark.Potts/sandbox/tmp
esmfdir: /scratch1/NCEPDEV/da/Mark.Potts/sandbox/esmf
hpcstackdir: /scratch1/NCEPDEV/da/Mark.Potts/hpc-stack
systemhpcstackdir: /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
modulelocation: /scratch1/NCEPDEV/da/Mark.Potts/sandbox/esmf-modules
artifactname: cpld_bmark_wave_v16
testnames: 
  test1: cpld_control_p7                                                                                                         
  test2: cpld_restart_p7                                                                                                         
  test3: cpld_2threads_p7                                                                                                        
  test4: cpld_decomp_p7                                                                                                          
  test5: cpld_control_wave_p7                                                                                                    
  test6: cpld_control_c192_p7                                                                                                    
  test7: cpld_restart_c192_p7                                                                                                    
  test8: cpld_control_c384_p7                                                                                                    
  test9: cpld_restart_c384_p7                                                                                                    
  test10: cpld_bmark_p7                                                                                                           

collectedfiles:
  regex1: PET*
  regex2: out
  regex3: err
  regex4: ESMF_Profile*
  regex5: log*
  regex6: nems*
