hostname: hera
collectiondir: /scratch1/NCEPDEV/stmp2/Mark.Potts/cpld_bmark_wave_v16
scheduler: "slurm"
artifactsdir: /scratch1/NCEPDEV/stmp2/Mark.Potts/ufs-test-artifacts
scriptdir: /scratch1/NCEPDEV/stmp2/Mark.Potts/ufs-test-artifacts/python_scripts
artifactname: cpld_bmark_wave_v16
collectedfiles:
  regex1: PET*
  regex2: out
  regex3: err
  regex4: ESMF_Profile*
  regex5: log*
  regex6: nems*
