hostname: chianti
collectiondir: /home/mpotts/cpld_bmark_sample
scheduler: "None"
artifactsdir: /home/mpotts/ufs-test-artifacts
scriptdir: /home/mpotts/ufs-test-artifacts/python_scripts
collectedfiles:
  regex1: PET*
  regex2: out
  regex3: err
  regex4: ESMF_Profile*
  regex5: log*
  regex6: nems*
